controllers:
    resource: ../src/Controller/
    type: attribute
app_order:
    path: /{type}
    controller: App\Controller\OrderController::index
    methods: GET
    defaults:
        type: json
    requirements:
        type: json|xml|csv
